import { migrationDatabase } from './database.mjs'
import { writeFile,readFile } from 'node:fs/promises'
const db=await migrationDatabase()
const {rows:columns}=await db.query(`select table_name,column_name,udt_name,is_nullable,column_default,is_identity from information_schema.columns where table_schema='public' order by table_name,ordinal_position`)
const names=[...new Set(columns.map(c=>c.table_name))]
const {rows:types}=await db.query(`select oid,typname from pg_type`)
const typeNames=new Map(types.map(t=>[t.oid,t.typname]))
function type(name){if(name.startsWith('_'))return `(${type(name.slice(1))})[]`;if(names.includes(name))return `Database['public']['Tables'][${JSON.stringify(name)}]['Row']`;if(['int2','int4','int8','float4','float8','numeric','oid'].includes(name))return 'number';if(name==='bool')return 'boolean';if(['json','jsonb'].includes(name))return 'Json';if(name==='void')return 'undefined';return 'string'}
const {rows:fks}=await db.query(`select c.conname,t.relname as table_name,ft.relname as referenced_relation,array(select a.attname from unnest(c.conkey) with ordinality k(n,i) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.n order by k.i) as columns,array(select a.attname from unnest(c.confkey) with ordinality k(n,i) join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.n order by k.i) as referenced_columns from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace ns on ns.oid=t.relnamespace join pg_class ft on ft.oid=c.confrelid where c.contype='f' and ns.nspname='public'`)
let text=`// Generated from the complete migration chain. Run npm run db:types.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\nexport type Database = { public: { Tables: {\n`
for(const table of names){const cols=columns.filter(c=>c.table_name===table);text+=`${JSON.stringify(table)}: {\n`;for(const shape of ['Row','Insert','Update']){text+=`${shape}: {\n`;for(const c of cols){const optional=shape==='Update'||shape==='Insert'&&(c.column_default!==null||c.is_nullable==='YES'||c.is_identity==='YES');text+=`${JSON.stringify(c.column_name)}${optional?'?':''}: ${type(c.udt_name)}${c.is_nullable==='YES'?' | null':''}\n`}text+='}\n'}text+='Relationships: [\n';for(const fk of fks.filter(f=>f.table_name===table&&names.includes(f.referenced_relation))){text+=`{ foreignKeyName: ${JSON.stringify(fk.conname)}; columns: ${JSON.stringify(fk.columns)}; isOneToOne: false; referencedRelation: ${JSON.stringify(fk.referenced_relation)}; referencedColumns: ${JSON.stringify(fk.referenced_columns)} },\n`}text+=']\n}\n'}
text+='}; Views: Record<never, never>; Functions: {\n'
const {rows:functions}=await db.query(`select p.proname,p.proargnames,p.proargmodes,p.proallargtypes,p.proargtypes::oid[] argtypes,p.prorettype,p.proretset,p.pronargdefaults from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prorettype <> 'trigger'::regtype order by p.proname`)
for(const f of functions){const ids=f.proallargtypes??f.argtypes,modes=f.proargmodes??ids.map(()=> 'i'),input=ids.map((id,i)=>({id,i})).filter(({i})=>['i','b','v'].includes(modes[i]));text+=`${JSON.stringify(f.proname)}: { Args: {`;for(let j=0;j<input.length;j++){const {id,i}=input[j];text+=`${JSON.stringify(f.proargnames?.[i]??`arg${i+1}`)}${j>=input.length-f.pronargdefaults?'?':''}: ${type(typeNames.get(id))} | null;`}text+='}; Returns: ';const output=ids.map((id,i)=>({id,i})).filter(({i})=>['o','b','t'].includes(modes[i]));if(output.length)text+='{'+output.map(({id,i})=>`${JSON.stringify(f.proargnames[i])}: ${type(typeNames.get(id))}`).join(';')+'}';else text+=type(typeNames.get(f.prorettype));if(f.proretset)text+='[]';text+=' };\n'}
text=text.replaceAll('Args: {}','Args: Record<never, never>');
text+='}; Enums: Record<never, never>; CompositeTypes: Record<never, never> } }\n'
if(process.argv.includes('--check')){if(await readFile('types/database.ts','utf8')!==text)throw Error('Database types are stale; run npm run db:types')}else await writeFile('types/database.ts',text)
await db.close()
console.log('Database types generated from PostgreSQL catalog')
