'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Opportunity={id:string;title:string;description:string;source_url:string;location:string;eligibility:string;compensation:string|null;deadline:string}
type Event={id:string;title:string;location:string;starts_at:string;details:string|null}
type Member={user_id:string;role:string;profiles:{username:string}|null}
export default function CircleCommunity({circleId,userId,ownerId,welcome:initialWelcome,rules:initialRules}:{circleId:string;userId:string;ownerId:string;welcome?:string|null;rules?:string|null}){
 const [opportunities,setOpportunities]=useState<Opportunity[]>([]),[events,setEvents]=useState<Event[]>([]),[saved,setSaved]=useState<string[]>([]),[going,setGoing]=useState<string[]>([]),[members,setMembers]=useState<Member[]>([])
 const [manager,setManager]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 const [welcome,setWelcome]=useState(initialWelcome??''),[rules,setRules]=useState(initialRules??'')
 useEffect(()=>{let active=true;const s=createClient();void Promise.all([
  s.from('circle_opportunities').select('*').eq('circle_id',circleId).gt('deadline',new Date().toISOString()).order('deadline').limit(50),
  s.from('circle_events').select('*').eq('circle_id',circleId).gt('starts_at',new Date().toISOString()).order('starts_at').limit(50),
  s.from('opportunity_saves').select('opportunity_id').eq('user_id',userId),s.from('event_rsvps').select('event_id').eq('user_id',userId),
  s.rpc('circle_manager',{target_circle:circleId}),
  s.from('circle_members').select('user_id,role,profiles:user_id(username)').eq('circle_id',circleId).order('created_at').limit(100),
 ]).then(([o,e,saved,rsvp,m,people])=>{if(!active)return;if(o.error||e.error||saved.error||rsvp.error||m.error||people.error){setError('Community details could not be loaded. Please retry.');return}setOpportunities(o.data??[]);setEvents(e.data??[]);setSaved((saved.data??[]).map(x=>x.opportunity_id));setGoing((rsvp.data??[]).map(x=>x.event_id));setManager(!!m.data);setMembers((people.data??[]) as unknown as Member[])})
 return()=>{active=false}
 },[circleId,userId,revision])
 async function run(action:()=>PromiseLike<{error:unknown}>){if(busy)return;setBusy(true);setError('');try{const {error}=await action();if(error)throw error;setRevision(n=>n+1)}catch{setError('Could not save this change. Your inputs are retained; please retry.')}finally{setBusy(false)}}
 async function publish(e:React.FormEvent<HTMLFormElement>,kind:'opportunity'|'event'){
  e.preventDefault();const form=e.currentTarget,data=new FormData(form),s=createClient(),value=(name:string)=>String(data.get(name)??'').trim()
  const when=new Date(value('date'));if(!Number.isFinite(when.getTime())||when.getTime()<=Date.now()){setError('Choose a future date.');return}
  const opportunityPayload={circle_id:circleId,created_by:userId,title:value('title'),description:value('description'),source_url:value('url'),location:value('location'),eligibility:value('eligibility'),compensation:value('compensation')||null,deadline:when.toISOString()};const eventPayload={circle_id:circleId,created_by:userId,title:value('title'),location:value('location'),details:value('description'),starts_at:when.toISOString()}
  if(busy)return;setBusy(true);setError('');const {error}=await (kind==='opportunity'?s.from('circle_opportunities').insert(opportunityPayload):s.from('circle_events').insert(eventPayload))
  if(error)setError('Publishing failed. Check your details and retry.');else{form.reset();setRevision(n=>n+1)}setBusy(false)
 }
 return <section className="space-y-4">
  <details className="card p-4" open={Boolean(initialWelcome||initialRules)}><summary className="font-bold">Start here</summary><p className="whitespace-pre-wrap mt-3">{initialWelcome||'Welcome! Introduce yourself, join a conversation, or share something you enjoy.'}</p><p className="whitespace-pre-wrap mt-3">{initialRules||'Respect other members. Ask before sharing private information. Report harassment and scams.'}</p>
   {userId===ownerId&&<form className="space-y-3 mt-4" onSubmit={e=>{e.preventDefault();void run(()=>createClient().from('circles').update({welcome,rules}).eq('id',circleId))}}><label className="block">Pinned welcome<textarea className="input" value={welcome} onChange={e=>setWelcome(e.target.value)} maxLength={2000}/></label><label className="block">Circle rules<textarea className="input" value={rules} onChange={e=>setRules(e.target.value)} maxLength={2000}/></label><button className="btn-primary" disabled={busy}>Save welcome & rules</button></form>}
  </details>
  <details className="card p-4"><summary className="font-bold">Opportunities ({opportunities.length})</summary><p className="text-sm my-3">Shared by Circle hosts. Check the original source before applying or sending money.</p>
   {opportunities.map(o=><article key={o.id} className="border-t py-4 space-y-2"><h3 className="font-bold">{o.title}</h3><p>{o.description}</p><p>{o.location} · {o.compensation||'Compensation not specified'}</p><p>Eligibility: {o.eligibility}</p><p>Deadline: {new Date(o.deadline).toLocaleString()}</p><a className="underline" href={o.source_url} target="_blank" rel="noopener noreferrer">Original source</a><div className="flex flex-wrap gap-2"><button className="btn-ghost" disabled={busy} onClick={()=>run(()=>saved.includes(o.id)?createClient().from('opportunity_saves').delete().match({opportunity_id:o.id,user_id:userId}):createClient().from('opportunity_saves').insert({opportunity_id:o.id,user_id:userId}))}>{saved.includes(o.id)?'Unsave':'Save'}</button><button className="btn-ghost" onClick={async()=>{try{await navigator.clipboard.writeText(o.source_url);setError('Source link copied.')}catch{setError('Open the original source to share its link.')}}}>Copy source link</button><button className="btn-ghost" disabled={busy} onClick={()=>{const reason=window.prompt('Why is this opportunity suspicious?');if(reason&&reason.trim().length>=5)void run(()=>createClient().from('opportunity_reports').insert({opportunity_id:o.id,reporter_id:userId,reason:reason.trim()}))}}>Report scam</button>{manager&&<button className="btn-ghost" disabled={busy} onClick={()=>run(()=>createClient().from('circle_opportunities').delete().eq('id',o.id))}>Remove</button>}</div></article>)}
   {!opportunities.length&&<p>No open opportunities yet.</p>}
   {manager&&<details className="mt-4"><summary>Add an opportunity</summary><form className="space-y-3 mt-3" onSubmit={e=>publish(e,'opportunity')}><label className="block">Title<input name="title" className="input" required minLength={3} maxLength={120}/></label><label className="block">Description<textarea name="description" className="input" required minLength={10} maxLength={2000}/></label><label className="block">Original source URL<input name="url" type="url" pattern="https://.*" className="input" required/></label><label className="block">Location or remote<input name="location" className="input" required minLength={2} maxLength={120}/></label><label className="block">Eligibility<input name="eligibility" className="input" required minLength={2} maxLength={500}/></label><label className="block">Compensation (optional)<input name="compensation" className="input" maxLength={120}/></label><label className="block">Deadline (your local time)<input name="date" className="input" type="datetime-local" required/></label><button className="btn-primary" disabled={busy}>Publish opportunity</button></form></details>}
  </details>
  <details className="card p-4"><summary className="font-bold">Events ({events.length})</summary>{events.map(e=><article key={e.id} className="border-t py-4 space-y-2"><h3 className="font-bold">{e.title}</h3><p>{new Date(e.starts_at).toLocaleString()} · {e.location}</p><p>{e.details}</p><button className="btn-ghost" disabled={busy} onClick={()=>run(()=>going.includes(e.id)?createClient().from('event_rsvps').delete().match({event_id:e.id,user_id:userId}):createClient().from('event_rsvps').insert({event_id:e.id,user_id:userId}))}>{going.includes(e.id)?'Going · Cancel RSVP':'RSVP'}</button>{manager&&<button className="btn-ghost" disabled={busy} onClick={()=>run(()=>createClient().from('circle_events').delete().eq('id',e.id))}>Remove event</button>}</article>)}
   {!events.length&&<p className="mt-3">No upcoming events.</p>}
   {manager&&<details className="mt-4"><summary>Plan an event</summary><form className="space-y-3 mt-3" onSubmit={e=>publish(e,'event')}><label className="block">Title<input name="title" className="input" required minLength={3} maxLength={120}/></label><label className="block">Where?<input name="location" className="input" required minLength={2} maxLength={200}/></label><label className="block">When? (your local time)<input name="date" className="input" type="datetime-local" required/></label><label className="block">Details<textarea name="description" className="input" maxLength={2000}/></label><button className="btn-primary" disabled={busy}>Create event</button></form></details>}
  </details>
  {userId===ownerId&&<details className="card p-4"><summary>Manage members</summary>{members.map(m=><div className="flex flex-wrap gap-3 items-center py-2" key={m.user_id}><Link href={`/profile/${m.user_id}`}>{m.profiles?.username??'Member'}</Link><span>{m.user_id===ownerId?'Owner':m.role}</span>{m.user_id!==ownerId&&<><button className="btn-ghost" disabled={busy} onClick={()=>run(()=>createClient().rpc('manage_circle_member',{target_circle:circleId,target_user:m.user_id,new_role:m.role==='moderator'?'member':'moderator'}))}>{m.role==='moderator'?'Remove moderator role':'Make moderator'}</button><button className="btn-ghost" disabled={busy} onClick={()=>run(()=>createClient().rpc('manage_circle_member',{target_circle:circleId,target_user:m.user_id,new_role:'remove'}))}>Remove member</button></>}</div>)}</details>}
  {error&&<p role="status">{error}</p>}
 </section>
}
