'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import type { Database } from '@/types/database'
type Action=Database['public']['Tables']['moderation_actions']['Row']
type Appeal=Database['public']['Tables']['moderation_appeals']['Row']
export default function ModerationAppeals({staff=false}:{staff?:boolean}){
 const [actions,setActions]=useState<Action[]>([]),[appeals,setAppeals]=useState<Appeal[]>([]),[reason,setReason]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
 useEffect(()=>{let active=true;const s=createClient();void (async()=>{const {data:{user}}=await s.auth.getUser();if(!user)return;const [a,b]=await Promise.all([s.from('moderation_actions').select('*').eq('target_user_id',user.id).order('created_at',{ascending:false}).limit(100),staff?s.from('moderation_appeals').select('*').eq('status','pending').order('created_at').limit(100):s.from('moderation_appeals').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(!active)return;if(a.error||b.error)setError('Decisions could not be loaded. Please retry.');else{setActions(a.data??[]);setAppeals(b.data??[])}})();return()=>{active=false}},[revision,staff])
 async function submit(id:string,approve?:boolean){if(busy)return;const text=reason[id]?.trim();if(!text||text.length<10){setError('Please give at least 10 characters of explanation.');return}setBusy(true);try{const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user)throw Error();const {error}=staff?await s.rpc('review_appeal',{appeal_id:id,approve:!!approve,explanation:text}):await s.from('moderation_appeals').insert({action_id:id,user_id:user.id,reason:text});if(error)throw error;setReason(old=>({...old,[id]:''}));setError('Saved.');setRevision(n=>n+1)}catch{setError(staff?'Review failed. A different moderator must review the original decision. Deleted messages cannot be restored.':'Appeal could not be submitted. Please retry.')}finally{setBusy(false)}}
 return <section className="card p-4 space-y-3"><h2 className="font-bold">{staff?'Pending appeals':'Moderation decisions & appeals'}</h2>{staff?appeals.map(a=><article key={a.id} className="border-t py-3 space-y-2"><p>{a.reason}</p><p>Action: {a.action_id}</p><label className="block">Review explanation<textarea className="input" maxLength={1000} value={reason[a.id]??''} onChange={e=>setReason(old=>({...old,[a.id]:e.target.value}))}/></label><button className="btn-ghost" disabled={busy} onClick={()=>submit(a.id,true)}>Accept appeal & reverse decision</button><button className="btn-ghost" disabled={busy} onClick={()=>submit(a.id,false)}>Decline appeal</button></article>):actions.map(a=><article key={a.id} className="border-t py-3 space-y-2"><p>{a.action.replaceAll('_',' ')} · {a.notes}</p>{appeals.some(p=>p.action_id===a.id)?<p>Appeal: {appeals.find(p=>p.action_id===a.id)?.status}</p>:['remove','suspend'].includes(a.action)&&<><label className="block">Why should this decision be reviewed?<textarea className="input" maxLength={1000} value={reason[a.id]??''} onChange={e=>setReason(old=>({...old,[a.id]:e.target.value}))}/></label><button className="btn-ghost" disabled={busy} onClick={()=>submit(a.id)}>Submit appeal</button></>}</article>)}{!(staff?appeals:actions).length&&<p>No {staff?'pending appeals':'decisions'}.</p>}{error&&<p role="status">{error}</p>}<button className="btn-ghost" onClick={()=>setRevision(n=>n+1)}>Refresh decisions</button></section>
}
